name: scratch-org-new

on:
  push:

jobs:
  create-empty-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: $GITHUB_REF
    - name: make empty commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit --allow-empty -m "empty commit"
        git push
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: $GITHUB_REF
    - name: Install Dependencies
      run: npm install sfdx-cli
    - name: Authenticate DevHub
      run: |
        echo "${{ secrets.SFDC_JWT_KEY }}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SFDC_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SFDC_DEVHUB_NAME }} --setdefaultdevhubusername --setalias devhub
    - name: Create Scratch Org
      run: node_modules/sfdx-cli/bin/run force:org:create --targetdevhubusername devhub --setdefaultusername --definitionfile config/project-scratch-def.json --setalias ciorg --durationdays 30 --wait 30
    - name: Generate Password
      run: node_modules/sfdx-cli/bin/run force:user:password:generate --targetusername ciorg
    - name: Display Scratch Org
      run: node_modules/sfdx-cli/bin/run force:org:display --targetusername ciorg
    - name: Deploy source
      run: node_modules/sfdx-cli/bin/run force:source:push --targetusername ciorg